apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    company: saveapis
    project: sso
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: NodePort
  