services:
  backend:
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: ..
      dockerfile: src/Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - HANGFIRE_REDIS_NAME=sso
      - HANGFIRE_REDIS_HOST=redis
      - HANGFIRE_REDIS_PORT=6379
      - HANGFIRE_REDIS_DATABASE=0
      - JWT_ISSUER=sso
      - JWT_AUDIENCE=sso
      - JWT_SECRET=youRandomStringWith64OrMoreCharactersAndShouldNotBeSharedWithUnknown
      - JWT_EXPIRATION_IN_HOURS=24
      - EASYCACHING_REDIS_HOST=redis
      - EASYCACHING_REDIS_PORT=6379
      - EASYCACHING_REDIS_DATABASE=1
      - EASYCACHING_REDIS_BUS_DATABASE=2
    ports:
      - "80:80"
  redis:
    image: redis:7.4.1-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
volumes:
  redis: