apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    company: saveapis
    project: sso
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      company: saveapis
      project: sso
      app: redis
  template:
    metadata:
      name: redis
      labels:
        company: saveapis
        project: sso
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0-M04-alpine3.21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
