GRAPHQL {{url}}
Authorization: Bearer {{token}}

query {
    projects {
        id
        createdAt
        updatedAt
        name
        description
        active
        users {
            id
            createdAt
            updatedAt
            firstName
            lastName
            email
            phone
            userName
            role
            active
        }
    }
}