name: CD (Stage)
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cd.stage.yml'
      - '.github/workflows/deploy.stage.yml'
      - 'src/Backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
          password: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          file: src/Backend/Dockerfile
          tags: |
            registry.digitalocean.com/saveapis/sso-backend:${{ github.sha }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_token=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_token=${{ secrets.HANGFIRE_PRO_TOKEN }}
            github_user=${{ github.actor }}
            github_token=${{ github.token }}